security:
  oauth2:
    client:
      clientId: 22CMQX
      clientSecret: 0f41f3009412cffee5c4dcb030cb2844
      accessTokenUri: https://api.fitbit.com/oauth2/token
      userAuthorizationUri: https://www.fitbit.com/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: header
      clientAuthenticationScheme: header
      scope: "activity heartrate location nutrition profile settings sleep social weight"
    resource:
      userInfoUri: https://api.fitbit.com/1/user/-/profile.json
fitbit:
  api:
    resource:
      activitiesUri: https://api.fitbit.com//1/user/-/activities/date/2018-02-18.json

logging:
  level:
    org.springframework.security: TRACE
