security:
  oauth2:
    client:
      clientId: 22CMQX
      clientSecret: 0f41f3009412cffee5c4dcb030cb2844
      accessTokenUri: https://api.fitbit.com/oauth2/token
      userAuthorizationUri: https://www.fitbit.com/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: header
      clientAuthenticationScheme: header
      scope: "activity heartrate location nutrition profile settings sleep social weight"
    resource:
      userInfoUri: https://api.fitbit.com/1/user/-/profile.json
fitbit:
  api:
    resource:
      activitiesUri: https://api.fitbit.com//1/user/-/activities/date/
      goalsUri: https://api.fitbit.com//1/user/-/activities/goals/
      lifetimeStatsUri: https://api.fitbit.com//1/user/-/activities.json
      sleepDateRangeUri: https://api.fitbit.com/1.2/user/-/sleep/date/
      heartRateDateRangeUri: https://api.fitbit.com/1/user/-/activities/heart/date/
      stepsDateRangeUri: https://api.fitbit.com/1/user/-/activities/steps/date/
      caloriesDateRangeUri: https://api.fitbit.com/1/user/-/activities/calories/date/
      distanceDateRangeUri: https://api.fitbit.com/1/user/-/activities/distance/date/
      floorsDateRangeUri: https://api.fitbit.com/1/user/-/activities/floors/date/


logging:
  level:
    org.springframework.security: TRACE


#spring:devtools:restart:exclude: public/**